server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: spring-gateway-demo
# spring cloud gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      # 路由配置，路由id，目标url，断言
      - id: session-demo
        uri: lb://spring-session
        predicates:
          - Path=/xx/**
        filters:
          - RewritePath=/xx(?<segment>/?.*), $\{segment}
          - name: Retry
            args:
              retries: 5
